routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','HomeController@landing')->name('landing');

Route::get('/home','HomeController@index')->name('home');

Route::resources([
    '/exam' => 'Admin\ExamController',
    '/quest' => 'Admin\QuestController',
    '/answer' => 'Admin\AnswerController',
    '/user-answer' => 'Admin\UserAnswerController'
]);

Route::get('/quiz/{exam:slug}','QuizController@startQuiz')
    ->name('quiz.start');

Route::get('/exam/show/{exam}','Admin\MoreOptionController@show')
    ->name('exam.up');

Route::get('/exam/hide/{exam}','Admin\MoreOptionController@hide')
    ->name('exam.down');

Route::post('/send','QuizController@save')
    ->name('exam.savequiz');

Auth::routes();

app/Exam.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Exam extends Model
{
    protected $fillable =[
        'name','slug','user_id','show'
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function quests(){
        return $this->hasMany(Quest::class);
    }

    public function answers(){
        return $this->hasManyThrough(Answer::class,Quest::class);
    }

    public function userAnswers(){
        return $this->hasManyThrough(User_answer::class,Quest::class);
    }
}

app/Http/Controllers/Admin/ExamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exam;
use App\Http\Controllers\Controller;
use App\Quest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Permission;

class ExamController extends Controller
{
    protected $table = [
      ['name' => 'name','title' => 'name'],
      ['name' => 'show','title' => 'show']
    ];

    public function __construct()
    {
        $this->middleware('admin');
        $this->authorizeResource(Exam::class,'exam');
    }

    /**
     * Display a listing of the resource.
     *
     *
     */
    public function index()
    {
        $exams = User::find(auth()->user()->id)->exams;
        return view('Admin.Exam.exam',[
            'data' => $exams,
            'table' => $this->table
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return response()->view('Admin.Exam.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     */
    public function store(Request $request)
    {
        $this->validateData($request->all())->validate();
        $slug = Str::of($request->name.'-'.auth()->user()->name.'-'.now())->slug();
        Exam::create([
            'name' => $request->name,
            'slug' => $slug,
            'user_id' => auth()->id(),
            'show' => 0
        ]);
        return redirect()->route('exam.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function show(Exam $exam)
    {
        $quest = Quest::where('exam_id',$exam->id)->with('answers')->get();
        return response()->view('Admin.Exam.view',[
            'title' => $exam->name,
            'quest' => $quest,
            'slug' => $exam->slug
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function edit(Exam $exam)
    {
        return response()->view('Admin.Exam.edit',[
           'data' => $exam
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Exam  $exam
     *
     */
    public function update(Request $request, Exam $exam)
    {
        $this->validateData($request->all())->validate();
        $slug = Str::of($request->name.'-'.auth()->user()->name.'-'.now())->slug();
        $exam->update([
            'name' => $request->name,
            'slug' => $slug
        ]);
        return redirect()->route('exam.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Exam  $exam
     *
     */
    public function destroy(Exam $exam)
    {
        $exam->answers()->delete();
        $exam->userAnswers()->delete();
        $exam->quests()->delete();
        $exam->delete();
        return redirect()->back();
    }

    public function validateData(Array $data){
        return Validator::make($data,[
            'name' => 'required|unique:App\Exam'
        ]);
    }
}

resources/views/Admin/Exam/create.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>add exam</h1>
@endsection

@section('content')
    <div class="row mt-1">
        <form method="post" action="{{route('exam.store')}}">
            @csrf
            <div class="form-group">
                <label for="name">quiz name</label>
                <input type="text" class="form-control" id="name" name="name">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/Admin/Exam/edit.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>edit exam</h1>
@endsection

@section('content')
    <div class="row mt-1">
        <form method="post" action="{{route('exam.update',$data->id)}}">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="name">quiz name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{$data->name}}">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/Admin/Exam/exam.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>your exams</h1>
@endsection

@section('content')
    <a class="btn btn-success" href="{{route('exam.create')}}">add</a>
    <div class="row mt-1">
        <table class="table">
            <thead>
            <tr>
                @foreach($table as $t)
                    <th scope="col">{{$t["title"]}}</th>
                @endforeach
                <th scope="col">tools</th>
            </tr>
            </thead>
            <tbody>
            @foreach($data as $d)
                <tr>
                    @foreach($table as $t)
                        <th scope="row">{{$d[$t["name"]]}}</th>
                    @endforeach
                    <th scope="row">
                        <div class="row">
                            <a href="{{route('exam.show',$d->id)}}" class="btn btn-success ml-2">view</a>
                            <a href="{{route('exam.edit',$d->id)}}" class="btn btn-warning ml-2">edit</a>
                            @if($d->show)
                                <a href="{{route('exam.down',$d->id)}}" class="btn btn-danger ml-2">uncheck</a>
                            @else
                                <a href="{{route('exam.up',$d->id)}}" class="btn btn-success ml-2">check</a>
                            @endif
                            <form action="{{route('exam.destroy',$d->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger ml-2">delete</button>
                            </form>
                        </div>
                    </th>
                </tr>
            @endforeach


            </tbody>
        </table>
    </div>
@endsection

resources/views/Admin/Exam/view.blade.php
@extends('adminlte::page')

@section('content_header')
    <div class="row">
        <h1 class="col">{{$title}}</h1>
        <p>
            link for share to people :
            {{route('quiz.start',$slug)}}
        </p>
    </div>
@endsection

@section('content')
<div class="row">
    @foreach($quest as $d)
        <div class="card col-12">
            <div class="card-title">{!! $d["quest"] !!}</div>
            <div class="card-body">
                    @foreach($d["answers"] as $q)
                        @if($d["id"] == $q["quest_id"])
                        <div class="row">
                            {{$q["answer"]}}
                        </div>
                        @endif
                    @endforeach
                <div class="row">
                    right answer : {{$d["answer"]}}
                </div>
                        <div class="row">
                            <div class="col">
                                <form action="{{route('quest.destroy',$d["id"])}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">remove</button>
                                </form>
                            </div>
                        </div>
            </div>
        </div>
    @endforeach
</div>
@endsection